/**
 * Server-only builder that turns a project's virtual file tree into a zip
 * that is ready to open in Android Studio via Capacitor.
 */
import { zipSync, strToU8 } from "fflate";

export type ExportFile = { path: string; content: string };

export type AndroidExportOptions = {
  appId: string;
  appName: string;
  projectName: string;
  webDir?: string;
  liveReloadUrl?: string | null;
};

const CAP_VERSION = "^8.4.2";

function capacitorConfig(o: AndroidExportOptions) {
  const server = o.liveReloadUrl
    ? `
  server: {
    url: "${o.liveReloadUrl}",
    cleartext: true,
    androidScheme: "https",
  },`
    : "";
  return `import type { CapacitorConfig } from "@capacitor/cli";

const config: CapacitorConfig = {
  appId: "${o.appId}",
  appName: "${o.appName}",
  webDir: "${o.webDir ?? "dist"}",
  bundledWebRuntime: false,${server}
  android: { allowMixedContent: ${Boolean(o.liveReloadUrl)} },
  ios: { contentInset: "always" },
};

export default config;
`;
}

function readme(o: AndroidExportOptions) {
  return `# ${o.appName} — Android Studio project

Generated by spok from the "${o.projectName}" workspace.

App ID: \`${o.appId}\`
Web build output: \`${o.webDir ?? "dist"}\`
Mode: ${o.liveReloadUrl ? `live-reload from ${o.liveReloadUrl}` : "bundled offline build (store ready)"}

## Prerequisites
- Node 20+ and bun (or npm)
- Android Studio (installs the Android SDK + platform-tools)
- JDK 17 (bundled with recent Android Studio)
- \`ANDROID_HOME\` exported in your shell

## One command
\`\`\`bash
bash setup-android.sh
\`\`\`

## Or step by step
\`\`\`bash
bun install
bun run build              # produces ${o.webDir ?? "dist"}/
bunx cap add android       # scaffolds android/ (first run only)
bunx cap sync android      # copies the web build + plugins into android/
bunx cap open android      # opens Android Studio
\`\`\`

## Run
In Android Studio pick an emulator or a USB device, then press Run.
CLI equivalent: \`bunx cap run android\`.

## Release (Play Store)
1. \`bun run build && bunx cap sync android\`
2. Android Studio -> Build -> Generate Signed Bundle / APK -> Android App Bundle
3. Create or reuse a keystore. Keep the keystore + passwords: every future
   update must be signed with the same key.

## Notes
- Re-run steps 1-2 after every web change; the APK bundles the web assets.
- If Gradle sync fails, use Android Studio -> Tools -> SDK Manager to install
  the latest Android SDK Platform + Build-Tools, then File -> Sync Project.
`;
}

function setupScript(o: AndroidExportOptions) {
  return `#!/usr/bin/env bash
# Build the web app and open it as a native Android project.
set -euo pipefail

command -v bun >/dev/null 2>&1 || { echo "bun not found: https://bun.sh"; exit 1; }
[ -n "\${ANDROID_HOME:-}\${ANDROID_SDK_ROOT:-}" ] || echo "warning: ANDROID_HOME is not set"

echo "==> installing dependencies"
bun install

echo "==> building web app"
bun run build

if [ ! -d android ]; then
  echo "==> adding android platform"
  bunx cap add android
fi

echo "==> syncing web build into android/"
bunx cap sync android

echo "==> opening Android Studio (${o.appName})"
bunx cap open android
`;
}

function patchPackageJson(raw: string | undefined, o: AndroidExportOptions) {
  let pkg: Record<string, any>;
  try {
    pkg = raw ? JSON.parse(raw) : {};
  } catch {
    pkg = {};
  }
  pkg.name = pkg.name ?? o.projectName.toLowerCase().replace(/[^a-z0-9-]/g, "-");
  pkg.scripts = {
    build: "vite build",
    ...(pkg.scripts ?? {}),
    "cap:add:android": "bunx cap add android",
    "cap:sync:android": "bunx cap sync android",
    "cap:open:android": "bunx cap open android",
    "cap:run:android": "bunx cap run android",
    "cap:build:android": "bun run build && bunx cap sync android && bunx cap open android",
  };
  pkg.dependencies = {
    ...(pkg.dependencies ?? {}),
    "@capacitor/core": CAP_VERSION,
    "@capacitor/android": CAP_VERSION,
  };
  pkg.devDependencies = {
    ...(pkg.devDependencies ?? {}),
    "@capacitor/cli": CAP_VERSION,
  };
  return JSON.stringify(pkg, null, 2) + "\n";
}

export function buildAndroidExportZip(
  files: ExportFile[],
  options: AndroidExportOptions,
): Uint8Array {
  const tree: Record<string, Uint8Array> = {};
  let pkgRaw: string | undefined;

  for (const f of files) {
    const path = f.path.replace(/^\.?\//, "");
    if (!path || path.startsWith("android/") || path.startsWith("ios/")) continue;
    if (path === "package.json") pkgRaw = f.content;
    if (path === "capacitor.config.ts" || path === "capacitor.config.json") continue;
    tree[path] = strToU8(f.content ?? "");
  }

  tree["package.json"] = strToU8(patchPackageJson(pkgRaw, options));
  tree["capacitor.config.ts"] = strToU8(capacitorConfig(options));
  tree["ANDROID_STUDIO.md"] = strToU8(readme(options));
  tree["setup-android.sh"] = strToU8(setupScript(options));

  return zipSync(tree, { level: 6 });
}

export function toBase64(bytes: Uint8Array): string {
  let binary = "";
  const chunk = 0x8000;
  for (let i = 0; i < bytes.length; i += chunk) {
    binary += String.fromCharCode(...bytes.subarray(i, i + chunk));
  }
  return btoa(binary);
}
